# Generated by Django 5.0.2 on 2024-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='account_photos')),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
