# Generated by Django 5.0.2 on 2024-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accdet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accdet',
            name='date',
        ),
        migrations.AddField(
            model_name='accdet',
            name='bank',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accdet',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accdet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='accdet',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accdet',
            name='photo',
            field=models.ImageField(null=True, upload_to='account_photos'),
        ),
    ]
